server:
  port: 8082

spring:
  application:
    name: config-server
  cloud:
    config:
      # 文件名默认以dev结尾，如abc-dev.properties
      #profile: dev
      label: master
      server:
        git:
          # URI一定要是仓库根目录
          uri: https://github.com/tito5460/practice
          # 注意github会在目录中间多出/tree/master/！tree/master/spring-cloud/config-server/config-demo是找不到的
          # 目录开头没有"/"
          searchPaths: spring-cloud/config-server/config-demo
          # 如果是公共仓库，用户名、密码可不填
          #username: 
          #password: 


#spring.application.name=config-server
#server.port=8888
#
## 文件名默认以dev结尾，如abc-dev.properties
##spring.cloud.config.profile=dev
## URI一定要是仓库根目录
#spring.cloud.config.server.git.uri=https://github.com/tito5460/practice
#spring.cloud.config.server.git.searchPaths=/tree/master/spring-cloud/config-server/config-demo
#spring.cloud.config.label=master
## 如果是公共仓库，可不填
##spring.cloud.config.server.git.username=
##spring.cloud.config.server.git.password=