server:
  port: 8082
spring:
  application:
    name: config-server

spring:
  cloud:
    config:
      #分支
      label: master
      server:
        git:
          #仓库URI
          uri: https://github.com/tito5460/practice/tree/master/spring-cloud/config-server
          #路径（会读取该目录下的所有配置文件）
          searchPaths: config-demo
          # 如果是公共仓库，不需要填用户名和密码
          #username: your username
          #password: your password