server:
  port: 8085

spring:
  application:
    name: feign-1

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8082/eureka/
      
feign:
  hystrix:
    # 开启断路器
    enabled: true