server:
  port: 8082

eureka:
  instance:
    hostname: localhost
  client:
    # 默认自动注册，server不注册自己
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

#logging.level.com.netflix.eureka=OFF
#logging.level.com.netflix.discovery=OFF